### ISSUE TITLE
Which backup will be used if multiple backup files exist?

### ISSUE THREAD

**Issue by peijianju** [IBM-Bluemix-Docs/RegistryImages#33]
Hi, my team is using ibmcloud-backup-restore to do a backup for our PVC. 
We have a cron job to do backup. So what ends up in my object store is something like this 
![image](https://user-images.githubusercontent.com/7400645/58258137-8f7d9480-7d48-11e9-866d-cfb6a01b2cc6.png)

When I do a restore, I notice that I only have to specify the backup name. But all my backup files have the same name, the only difference is the timestamp as in the figure.

My questions would be which backup it actually using? Can I use a specific backup?

Thank you

**Comment by SueGraham** [comment]
See also: https://github.ibm.com/Bluemix/Documentation-content/issues/5239

**Comment by Nadine2016** [comment]
Reached out to the user. Answer is: 

For full backup, it will always take the latest full backup. 
For incremental, it will always take the last full backup and all increments up to today where you restore. 
You cannot specify a specific date. 

Will add this info to the docs. closing.
